import { Button, Heading } from "@chakra-ui/react";
import Head from "next/head";
import React, { useState } from "react";

const Counter = () => {
  let [counter, setCounter] = useState(0);
  return (
    <>
      <Head>
        <title>Counter App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <Heading as={"h1"}>Count: {counter}</Heading>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            gap: "10%",
          }}
        >
          <Button
            disabled={counter == 0}
            onClick={() => setCounter(counter - 1)}
          >
            DEC
          </Button>
          <Button onClick={() => setCounter(counter + 1)}>INC</Button>
          <Button
            disabled={counter == 0}
            onClick={() => setCounter((counter = 0))}
          >
            RESET
          </Button>
        </div>
      </div>
    </>
  );
};

export default Counter;
