import { Box, Button, Heading } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";

const Todo = ({ todos }) => {
  //   const [todos, setTodos] = useState([]);

  //   const getTodos = async () => {
  //     const response = await fetch("http://localhost:8080/todos");
  //     let data = await response.json();
  //     setTodos(data);
  //   };

  //   useEffect(() => {
  //     getTodos();
  //   }, []);

  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display={"flex"} flexDirection={"column"} alignItems={"center"}>
        <Button colorScheme="teal">Todo</Button>
        {todos.map((todo) => (
          <Heading as={"h6"} fontSize="xl" key={todo.id}>
            {todo.value}
          </Heading>
        ))}
      </Box>
    </>
  );
};

export async function getServerSideProps() {
  const response = await fetch("http://localhost:8080/todos");
  let data = await response.json();
  return {
    props: {
      todos: data,
    },
  };
}

export default Todo;

//how to center the div in react.js
