import React from "react";
import Head from "next/head";
// import Link from "next/link";
import { useRouter } from "next/router";

const Page = ({ blogs = [] }) => {
  const router = useRouter();

  const handleClick = (id) => {
    router.push(`/${id}`);
  };
  return (
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {blogs.map((blog) => (
          <div key={blog.id}>
            <h1 onClick={() => handleClick(blog.id)}>{blog.title}</h1>
          </div>
        ))}
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const response = await fetch("http://localhost:8080/blogs");
  let data = await response.json();
  return {
    props: {
      blogs: data,
    },
  };
}

export default Page;
