import Head from "next/head";
import React from "react";

const Page = ({ movies }) => {
  return (
    <>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {movies.map((movie) => (
            <div key={movie.imdbID}></div>
          ))}
        </div>
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const {
    params: { id },
  } = context;

  const response = await fetch("http://localhost:8080/movies");
  let data = await response.json();
  return {
    props: {
      movies: data,
    },
  };
}

export default Page;
